trigger:
  branches:
    include:
      - main  # Triggers pipeline on the main branch

pool:
  vmImage: 'macos-latest'  # You can also use 'ubuntu-latest' for Linux if you're not relying on macOS

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    options: ''
    tasks: 'assembleDebug'  # You can use 'assembleRelease' for a release build
    publishJUnitResults: true
    testResultsFiles: '**/build/test-results/testDebugUnitTest/*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '**/*.apk'  # Publishes the generated APK
    ArtifactName: 'drop'
    publishLocation: 'Container'
